"""Modelo de datos unificado para todo el proyecto."""
from dataclasses import dataclass, field
from typing import Optional

UNIFIED_SCHEMA = {
    'source': str,
    'source_type': str,
    'country': str,
    'country_name': str,
    'region': str,
    'year': int,
    'job_title': str,
    'role_category': str,
    'experience_level': str,
    'employment_type': str,
    'salary_local': float,
    'currency': str,
    'salary_usd': float,
    'remote_ratio': int,
    'company_size': str,
    'company_location': str,
    'latitude': float,
    'longitude': float,
}

UNIFIED_COLUMNS = list(UNIFIED_SCHEMA.keys())

ROLE_CATEGORIES = {
    'data scientist': 'Data Scientist',
    'data engineer': 'Data Engineer',
    'data analyst': 'Data Analyst',
    'machine learning': 'Machine Learning Engineer',
    'ml engineer': 'Machine Learning Engineer',
    'ai engineer': 'AI Engineer',
    'ai scientist': 'AI Engineer',
    'business intelligence': 'Business Intelligence',
    'data architect': 'Data Architect',
    'analytics engineer': 'Analytics Engineer',
    'data manager': 'Data Manager',
    'data specialist': 'Data Specialist',
    'data science manager': 'Data Science Manager',
    'data engineering manager': 'Data Engineering Manager',
    'data analytics manager': 'Analytics Manager',
    'head of data': 'Head of Data',
    'head of data science': 'Head of Data',
    'research scientist': 'Research Scientist',
    'computer vision': 'Computer Vision Engineer',
    'nlp engineer': 'NLP Engineer',
    'backend engineer': 'Backend Engineer',
    'frontend engineer': 'Frontend Engineer',
    'fullstack engineer': 'Fullstack Engineer',
    'devops': 'DevOps Engineer',
    'mobile': 'Mobile Engineer',
    'qa': 'QA Engineer',
    'sysadmin': 'SysAdmin',
    'security': 'Security Engineer',
    'cloud': 'Cloud Engineer',
}

EXPERIENCE_MAP = {
    'en': 'Entry',
    'entry level': 'Entry',
    'entry': 'Entry',
    'junior': 'Entry',
    '<2': 'Entry',
    'mi': 'Mid',
    'mid': 'Mid',
    'mid-senior level': 'Mid',
    '2-5': 'Mid',
    'se': 'Senior',
    'senior': 'Senior',
    'sr': 'Senior',
    '5-10': 'Senior',
    'ex': 'Executive',
    'executive': 'Executive',
    'director': 'Executive',
    'lead': 'Senior',
    'manager': 'Senior',
    'staff': 'Senior',
    'principal': 'Executive',
}

REGIONS = {
    'US': 'North America', 'CA': 'North America', 'MX': 'LATAM',
    'ES': 'Europe', 'GB': 'Europe', 'DE': 'Europe', 'FR': 'Europe',
    'IT': 'Europe', 'NL': 'Europe', 'PT': 'Europe', 'IE': 'Europe',
    'AT': 'Europe', 'BE': 'Europe', 'CH': 'Europe', 'DK': 'Europe',
    'FI': 'Europe', 'GR': 'Europe', 'NO': 'Europe', 'PL': 'Europe',
    'SE': 'Europe', 'RO': 'Europe', 'HU': 'Europe', 'CZ': 'Europe',
    'BG': 'Europe', 'HR': 'Europe', 'EE': 'Europe', 'LU': 'Europe',
    'MT': 'Europe', 'RS': 'Europe', 'SI': 'Europe', 'SK': 'Europe',
    'LT': 'Europe', 'LV': 'Europe', 'AL': 'Europe', 'BA': 'Europe',
    'BR': 'LATAM', 'AR': 'LATAM', 'CL': 'LATAM', 'CO': 'LATAM',
    'PE': 'LATAM', 'UY': 'LATAM', 'EC': 'LATAM', 'CR': 'LATAM',
    'PA': 'LATAM', 'BO': 'LATAM', 'PY': 'LATAM', 'VE': 'LATAM',
    'IN': 'Asia', 'CN': 'Asia', 'JP': 'Asia', 'SG': 'Asia',
    'KR': 'Asia', 'HK': 'Asia', 'MY': 'Asia', 'PH': 'Asia',
    'PK': 'Asia', 'VN': 'Asia', 'IL': 'Asia', 'AE': 'Asia',
    'TR': 'Asia', 'SA': 'Asia', 'QA': 'Asia', 'KW': 'Asia',
    'NG': 'Africa', 'KE': 'Africa', 'ZA': 'Africa', 'DZ': 'Africa',
    'AU': 'Oceania', 'NZ': 'Oceania',
}
